openapi: 3.0.0
info:
  title: API's OpenData do Open Banking Brasil
  description: As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
  version: 1.0.0-rc5
  contact:
    email: apiteam@swagger.io
servers:
  - url: 'http://api.banco.com.br/open-banking/accounts/v1'
tags:
  - name: Accounts Identification
  - name: Accounts Balance
  - name: Accounts Transactions
  - name: Accounts Overdraft Limits
paths:
  /accounts-identification:
    get:
      tags:
        - Accounts Identification
      summary: Dados de identificação de uma conta
      description:  Obtém dados que identificam uma conta
      operationId: getAccountsIdentification
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pageSize"
      responses:
        '200':
          description: Dados de identificação de conta obtidos com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseAccountsIdentification'
  
components:
  schemas:
    ResponseAccountsIdentification:
      $ref: ./schemas/ResponseAccountsIdentification.yaml
  securitySchemes:
    $ref: "./schemas/securitySchemes.yaml"
  parameters:
    $ref: "./schemas/parameters.yaml"
